name: rbfe-demo
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - setuptools<82
  - openff-toolkit
  - rdkit
  - lomap2
  - networkx
  - alchemlyb
  - pandas
  - numpy
  - matplotlib
  - ipykernel
  - py3dmol
  - gromacs
